---
- name: This is my first Play.
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  vars:
    message: "Hello World!"

  tasks:
    - name: Display Message
      debug:
        msg: '{{ message }}'

    - name: Display IP
      debug:
        var: ansible_default_ipv4.address
       

- name: This is my second Play.
  hosts: '{{ target|lower }}'
  gather_facts: true
  become: false

  tasks:
    - name: Display IP
      debug:
        var: ansible_default_ipv4.address


