---
- name: This is my first playbook.
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  vars:
    message: "Hello World!"

  tasks:
    - name: Display Message
      debug:
        msg: '{{ message }}'

